[2017-11-05 11:20:30] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:20:31] console.DEBUG: Command "server:start" exited with code "1" {"command":"server:start","code":1} []
[2017-11-05 11:26:57] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:27:37] console.DEBUG: Command "server:stop" exited with code "1" {"command":"server:stop","code":1} []
[2017-11-05 11:27:49] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:29:08] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php\",\"line\":47,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/var/cache/dev/appDevDebugProjectContainer.php\",\"line\":2229,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpFoundation\\\\Session\\\\Storage\\\\Handler\\\\NativeFileSessionHandler\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:29:08] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/uriy/www/symfony-blog-IvAr/var/sessions/dev"" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/uriy/www/symfony-blog-IvAr/var/sessions/dev\" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2017-11-05 11:29:10] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php\",\"line\":47,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/var/cache/dev/appDevDebugProjectContainer.php\",\"line\":2229,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpFoundation\\\\Session\\\\Storage\\\\Handler\\\\NativeFileSessionHandler\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:29:10] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/uriy/www/symfony-blog-IvAr/var/sessions/dev"" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/uriy/www/symfony-blog-IvAr/var/sessions/dev\" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2017-11-05 11:33:10] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:33:29] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php\",\"line\":47,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/var/cache/dev/appDevDebugProjectContainer.php\",\"line\":2229,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpFoundation\\\\Session\\\\Storage\\\\Handler\\\\NativeFileSessionHandler\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:33:29] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/uriy/www/symfony-blog-IvAr/var/sessions/dev"" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/uriy/www/symfony-blog-IvAr/var/sessions/dev\" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2017-11-05 11:33:30] php.DEBUG: Warning: mkdir(): Permission denied {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php\",\"line\":47,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/var/cache/dev/appDevDebugProjectContainer.php\",\"line\":2229,\"function\":\"__construct\",\"class\":\"Symfony\\\\Component\\\\HttpFoundation\\\\Session\\\\Storage\\\\Handler\\\\NativeFileSessionHandler\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:33:30] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Session Storage was not able to create directory "/home/uriy/www/symfony-blog-IvAr/var/sessions/dev"" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php line 48 {"exception":"[object] (RuntimeException(code: 0): Session Storage was not able to create directory \"/home/uriy/www/symfony-blog-IvAr/var/sessions/dev\" at /home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php:48)"} []
[2017-11-05 11:36:12] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"/home/uriy/www/symfony-blog-IvAr/vendor/symfony/symfony/src/Symfony/Bundle/WebServerBundle/WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-11-05 11:36:24] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-11-05 11:36:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-11-05 11:36:25] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"efa6f3","_route":"_wdt"},"request_uri":"http://localhost:8000/_wdt/efa6f3","method":"GET"} []
[2017-11-05 15:30:04] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: could not find driver" {"error":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: could not find driver"} []
[2017-11-05 15:30:04] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 15:33:56] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: could not find driver" {"error":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: could not find driver"} []
[2017-11-05 15:33:56] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 15:40:36] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2017-11-05 15:40:36] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 15:49:23] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 15:49:23] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 16:00:31] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 16:00:31] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 16:14:21] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 16:14:21] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 16:16:33] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 16:16:33] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 17:15:34] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 17:15:35] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 17:48:58] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 17:48:58] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 18:08:17] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 18:08:17] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 20:59:50] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 20:59:50] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 21:50:30] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 21:50:30] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-05 23:18:48] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-05 23:18:48] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2017-11-06 22:43:59] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /home/uriy/www/symfony-blog-IvAr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)","command":"doctrine:database:create","message":"An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)"} []
[2017-11-06 22:43:59] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
